import 'dart:convert';
import 'dart:io';

import 'package:path_provider/path_provider.dart';

import 'package:adv_basics/models/generated_variant.dart';
import 'package:adv_basics/models/quiz_model.dart';

class GoogleFormsExportService {
  const GoogleFormsExportService();

  Future<GoogleFormsExportResult> exportVariant({
    required QuizModel quiz,
    required GeneratedVariant variant,
  }) async {
    final dir = await getApplicationDocumentsDirectory();
    final stamp = DateTime.now().millisecondsSinceEpoch;
    final baseName = 'google_forms_${quiz.id}_${variant.id}_$stamp';
    final jsonPath = '${dir.path}/$baseName.json';
    final scriptPath = '${dir.path}/$baseName.gs';

    final payload = _buildPayload(quiz: quiz, variant: variant);
    final jsonFile = File(jsonPath);
    await jsonFile.writeAsString(
      const JsonEncoder.withIndent('  ').convert(payload),
      flush: true,
    );

    final scriptFile = File(scriptPath);
    await scriptFile.writeAsString(
      _buildAppsScript(payload),
      flush: true,
    );

    return GoogleFormsExportResult(
      jsonPath: jsonPath,
      scriptPath: scriptPath,
    );
  }

  Map<String, dynamic> _buildPayload({
    required QuizModel quiz,
    required GeneratedVariant variant,
  }) {
    return {
      'title': '${quiz.title} - ${variant.id}',
      'description': 'Generated by Quizzer',
      'questions': variant.questions.map((question) {
        final imageRef = question.imageRef.trim();
        final httpImage = imageRef.startsWith('http://') || imageRef.startsWith('https://');
        return {
          'prompt': question.composedPrompt,
          'options': question.options
              .map((option) => {
                    'text': option.composedText,
                    'isCorrect': option.id == question.correctOptionId,
                  })
              .toList(),
          'imageUrl': httpImage ? imageRef : null,
          'hasNonHttpImage': imageRef.isNotEmpty && !httpImage,
        };
      }).toList(),
    };
  }

  String _buildAppsScript(Map<String, dynamic> payload) {
    final encodedPayload = jsonEncode(payload);
    return '''
/**
 * 1) Open https://script.google.com/
 * 2) Create a new project.
 * 3) Paste this file and run buildQuizzerForm().
 * 4) Approve permissions, then open the logged URLs.
 */
function buildQuizzerForm() {
  const payload = $encodedPayload;
  const form = FormApp.create(payload.title);
  form.setDescription(payload.description || '');
  form.setIsQuiz(true);
  form.setCollectEmail(false);

  payload.questions.forEach((q, index) => {
    const item = form.addMultipleChoiceItem();
    item.setTitle('Q' + (index + 1) + '. ' + q.prompt);
    item.setRequired(true);

    const choices = (q.options || []).map((o) => item.createChoice(o.text, !!o.isCorrect));
    if (choices.length > 0) {
      item.setChoices(choices);
    }
    item.setPoints(1);

    if (q.imageUrl) {
      try {
        const blob = UrlFetchApp.fetch(q.imageUrl).getBlob();
        const imageItem = form.addImageItem();
        imageItem.setImage(blob);
        imageItem.setTitle('Image for Q' + (index + 1));
      } catch (e) {
        Logger.log('Failed to fetch image for question ' + (index + 1) + ': ' + e);
      }
    } else if (q.hasNonHttpImage) {
      const noteItem = form.addParagraphTextItem();
      noteItem.setTitle('Image note for Q' + (index + 1));
      noteItem.setHelpText('Original question contains a local/embedded image that Google Forms cannot fetch directly.');
    }
  });

  Logger.log('Edit URL: ' + form.getEditUrl());
  Logger.log('Published URL: ' + form.getPublishedUrl());
}
''';
  }
}

class GoogleFormsExportResult {
  const GoogleFormsExportResult({
    required this.jsonPath,
    required this.scriptPath,
  });

  final String jsonPath;
  final String scriptPath;
}
